### ISSUE TITLE
Device registration does not work with Dell Latitude 3180

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#176]
After entering the puavo domain name the installation crashes.

```
root@3180depian001:~$ puavo-register --force

	-=< Puavo Devices Client >=-

Puavo server name: [toimisto.opinsys.fi] 
/usr/lib/ruby/2.3.0/openssl/buffering.rb:178:in `sysread_nonblock': SSL_read: sslv3 alert bad record mac (OpenSSL::SSL::SSLError)
	from /usr/lib/ruby/2.3.0/openssl/buffering.rb:178:in `read_nonblock'
	from /usr/lib/ruby/2.3.0/net/protocol.rb:154:in `rbuf_fill'
	from /usr/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
	from /usr/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
	from /usr/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
	from /usr/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
	from /usr/lib/ruby/2.3.0/net/http.rb:1437:in `block in transport_request'
	from /usr/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
	from /usr/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
	from /usr/lib/ruby/2.3.0/net/http.rb:1407:in `request'
	from /usr/sbin/puavo-register:495:in `block in get'
	from /usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /usr/sbin/puavo-register:492:in `get'
	from /usr/sbin/puavo-register:443:in `get_devicetypes'
	from /usr/sbin/puavo-register:420:in `initialize'
	from /usr/sbin/puavo-register:276:in `new'
	from /usr/sbin/puavo-register:276:in `connect_to_puavo'
	from /usr/sbin/puavo-register:342:in `register_to_server'
	from /usr/sbin/puavo-register:561:in `register'
	from /usr/sbin/puavo-register:654:in `<main>'

```

**Comment by asokero** [comment]
This has been solved by changing required ssl protocol versions.
