### ISSUE TITLE
Linux version of the EShare application crashes

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#621]
App source: https://eshare.app/ (ubuntu app)

The problem:
- When EShare is used on puavo-os it crashes after screen share pin is set and casting to external eshare capable display is started. This happens on both Bullseye and Bookworm.
- Casting works fine with standard Debian Bullseye

In the event of the crash the following logs were collected
```
System logs:

[36055.151914] QThread[85766]: segfault at 460 ip 00007fe159951c44 sp 00007fe0e7fcf8f0 error 4 in libavformat.so.58[7fe1597b2000+223000] [36055.151956] Code: 45 89 e7 e9 28 f5 ff ff 45 89 e7 e9 18 f5 ff ff 66 0f 1f 44 00 00 41 57 41 56 41 55 41 54 49 89 fc 55 53 49 89 f5 48 83 ec 18 <41> f6 84 24 60 04 00 00 01 48 8b bf 48 05 00 00 48 8b 6f 08 0f 85
```

Application logs
```
Create settings.ini
language is : 42
[v7.4.0324]D 2023-06-21 09:46:37.059 ************************ v7.4.0324 wayland: false *********************************************************** 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
getAutoaccept()  "1"
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[v7.4.0324]D 2023-06-21 09:46:38.093 "/home/ajt/Downloads" 
RuntimeConfig IP "10.249.0.75 uid 331315"
start send password...
ret: 1
"check success\r\n\r\n"
emit  SignalNotifyStatus(PS_STATUS_OK);
PS_STATUS_OK
[v7.4.0324]I 2023-06-21 09:46:52.115 startNetworkMonitor 
[v7.4.0324]D 2023-06-21 09:46:53.938 startRTSP start 
desktop_rtsp wait thread start
  MirrorStateManager(0x55afaed384c0) ....run....
[v7.4.0324]D 2023-06-21 09:46:53.938 RTSP Thread start 
[v7.4.0324]D 2023-06-21 09:46:53.939 RTSP connect start 
[v7.4.0324]D 2023-06-21 09:46:53.944 The requestdescribe is reconnecting: false 
[v7.4.0324]D 2023-06-21 09:46:53.953 Describe data_len 0 
[v7.4.0324]D 2023-06-21 09:46:53.954 ret:  0 
[v7.4.0324]D 2023-06-21 09:46:53.954 desktop_rtsp startMirror begin
 
[v7.4.0324]D 2023-06-21 09:46:53.954 IP: 10.249.0.75 uid 331315 Name: at-laptop-01 Mac: f430b9c71386 
[v7.4.0324]D 2023-06-21 09:46:53.958 startRTSP over-- 
[v7.4.0324]D 2023-06-21 09:46:54.293 encoder video width: 1920 ,height : 1080 
[v7.4.0324]D 2023-06-21 09:46:54.294 avcodec_find_encoder = 0x7f9a8d583020 
[v7.4.0324]D 2023-06-21 09:46:54.295 Code name is  libx264 ,cpuCount is 8 
[v7.4.0324]D 2023-06-21 09:46:54.342 desktop_namage startMirror begin  
[v7.4.0324]D 2023-06-21 09:46:54.342 desktop_namager wait thread start 
[v7.4.0324]D 2023-06-21 09:46:54.343 desktop_namager::doWork 
[v7.4.0324]D 2023-06-21 09:46:54.347 reinit encoder begin 
[v7.4.0324]D 2023-06-21 09:46:54.350 xxxCouldn't open input stream.
 
[v7.4.0324]D 2023-06-21 09:46:54.350  x11 screen capture init falied 
[v7.4.0324]D 2023-06-21 09:46:54.350 encoder video width: 1920 ,height : 1080 
[v7.4.0324]D 2023-06-21 09:46:54.350 avcodec_find_encoder = 0x7f9a8d583020 
[v7.4.0324]D 2023-06-21 09:46:54.351 Code name is  libx264 ,cpuCount is 8 
[v7.4.0324]D 2023-06-21 09:46:54.363 desktop_namage startMirror over  
 data  bplist00� �     	 �!Wstreams � XdataPort `Ttype�  [controlPort/  
*(  2 
[v7.4.0324]D 2023-06-21 09:46:54.390 Audio pcm Port:  25123 
[v7.4.0324]D 2023-06-21 09:46:54.391 desktop_audiotcp startRecorder begin 
[v7.4.0324]D 2023-06-21 09:46:54.419 desktop_audiotcp dowork start 
Speicherzugriffsfehler
```

Could this be some problem caused by multiarc/32bit library?

**Comment by asokero** [comment]
Some comments from TNurmi few months ago:

```
additionally, I tried to debug the crash further,
a backtrace:
```

```
(gdb) bt
#0  0x00007ffff79252e4 in av_read_frame (s=0x0, pkt=0x0) at src/libavformat/utils.c:1788
#1  0x00005555554b7a91 in X11ScreenCapture::getAframe() (this=0x7fff90012f80) at ../x11_util/x11screencapture.cpp:137
#2  0x000055555545cfd1 in desktop_namager::doWork() (this=0x7fff900038c0) at ../desktop_namager.cpp:475
#3  0x00005555554be78b in desktop_namager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x7fff900038c0, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fff89bf01f0) at moc_desktop_namager.cpp:81
#4  0x00007ffff3480ddf in void doActivate<false>(QObject*, int, void**) () at /opt/EShare/lib/libQt5Core.so.5
#5  0x00007ffff325c9d7 in QThread::started(QThread::QPrivateSignal) () at /opt/EShare/lib/libQt5Core.so.5
#6  0x00007ffff325eb1c in QThreadPrivate::start(void*) () at /opt/EShare/lib/libQt5Core.so.5
#7  0x00007ffff3190ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff2d83a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

and a local frame data
#0  X11ScreenCapture::getAframe() (this=0x7fff90015400) at ../x11_util/x11screencapture.cpp:137
        got_picture = 0
#1  0x000055555545cfd1 in desktop_namager::doWork() (this=0x7fff90003f20) at ../desktop_namager.cpp:475
        ret = 0
        time = 609187
        encodeTime = 0
        grabberTime = 0
        sendTime = 0
        internal = 50
        needWait = 1
        encode_size = 1048576
        delay = 609119
        pixels = 0x0
        __PRETTY_FUNCTION__ = "void desktop_namager::doWork()"
#2  0x00005555554be78b in desktop_namager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x7fff90003f20, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fff89bf01f0) at moc_desktop_namager.cpp:81
        _t = 0x7fff90003f20
#3  0x00007ffff3480ddf in void doActivate<false>(QObject*, int, void**) () at /opt/EShare/lib/libQt5Core.so.5
#4  0x00007ffff325c9d7 in QThread::started(QThread::QPrivateSignal) () at /opt/EShare/lib/libQt5Core.so.5
#5  0x00007ffff325eb1c in QThreadPrivate::start(void*) () at /opt/EShare/lib/libQt5Core.so.5
#6  0x00007ffff3190ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140735504389888, 1904597340778528536, 140736111566398, 140736111566399, 140735504384832, 8396800, -1904619882821845224, -1904570730786586856}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007ffff2d83a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

```
suggest that desktop_namager tries to feed invalid data to libavformat (as is to be expected with log entry [v7.4.0324]D 2023-08-17 09:39:54.266  x11 screen capture init falied). We also tried a gnome flashback metacity desktop session, with corresponding results. I am guessing that desktop_namager / X11ScreenCapture make some invalid assumptions about the environment / try to read un-set environment variables or something similar.
```

**Comment by asokero** [comment]
The problem with Eshare on Puavo OS seems to be that we use XOrg (X11) display server on both the GDM login screen and on the Gnome desktop environment. On standard Ubuntu or Debian this is by default Wayland or combination of Wayland on GDM and X11 on the desktop.

Currently we are able to work around the problem by temporarily patching the EShare binary with the following command: sed -i 's/:0.0/:1.0/g' /opt/EShare/EShare

This results in a workaround fix for the EShare application that works on our system (both GDM and Gnome running in xorg/x11).

The real fix should be done to the Eshare client and it should use for example environment variables ($DISPLAY) to identify the display that should be mirrored via eshare. 

Currently the application makes a false assumption that the display is always located at :0.0. But this value could be something else on different systems. For example in a system running both GDM and Desktop environment via Xorg (X11) this value is :1.0 (such as on Puavo OS)


To reproduce the problem on standard Debian (or Ubuntu) you can do the following:
```
- Install standard Debian Bullseye or Bookworm (and most likely also Ubuntu) with Gnome Desktop on a standard laptop
- Edit file /etc/gdm3/daemon.conf
- Set the value WaylandEnable=false (remove comment in the beginning of the line)
- Reboot the computer
- Login on the desktop with Xorg (X11)
- Install Eshare client
- Run eshare and and mirror your screen to a eshare capable display

```

In this case the application should crash and result a black screen on the monitor.
